let artworks=[];
let filteredArtworks=[];
let currentLanguage=localStorage.getItem('kelk_language')||'fa';
const $=id=>document.getElementById(id);
const gallery=$('galleryGrid'), count=$('count'), searchInput=$('search');
const artistFilter=$('artistFilter'), poetFilter=$('poetFilter'), scriptFilter=$('scriptFilter'), formatFilter=$('formatFilter'), techniqueFilter=$('techniqueFilter'), periodFilter=$('periodFilter');
const languageToggle=$('languageToggle');
const labels={
 fa:{gallery:'نگارخانه',galleryTitle:'آثار خوشنویسی',library:'کتابخانه',libraryTitle:'منابع و مراجع',libraryIntro:'منابع شعر، کتاب‌ها، مرقعات و مراجع پژوهشی ثبت‌شده در آرشیو.',events:'رویدادها',eventSoon:'به‌زودی',eventTitle:'رویدادهای کلک دبیر',eventText:'در این بخش، نمایشگاه‌ها، نشست‌ها، کارگاه‌ها و رویدادهای مرتبط با خوشنویسی و پژوهش‌های آرشیوی معرفی خواهند شد.',about:'درباره ما',aboutTitle:'کلک دبیر',aboutText:'«کلک دبیر» درگاهی است برای مشق نظری خوشنویسی که با قابلیت جستجو، امکان دسترسی سریع را به ترکیب انتخابی بزرگان نستعلیق و شکسته‌نستعلیق از کلمات و عبارات فراهم می‌کند.',search:'جستجو در شعر، خوشنویس، شاعر، خط، قالب، تکنیک، دوره، مکان و منابع…',hint:'می‌توانید چند کلیدواژه را هم‌زمان جستجو کنید.',artists:'همه خوشنویسان',poets:'همه شاعران',scripts:'همه خطوط',formats:'همه قالب‌ها',techniques:'همه تکنیک‌ها',periods:'همه دوره‌ها',count:'تعداد آثار',poet:'شاعر',artist:'خوشنویس',script:'خط',format:'قالب',year:'سال',period:'دوره',place:'مکان',tech:'تکنیک/تزئین',poemSource:'منبع شعر',imageSource:'منبع عکس',additionalSource:'منبع اضافه',description:'توضیحات',date:'تاریخ ثبت',view:'مشاهده اثر',none:'اثری با این مشخصات پیدا نشد.',noText:'بدون متن توصیفی',noData:'داده‌ای برای نمایش وجود ندارد.',close:'بستن',open:'مشاهده منبع',curator:'گرداننده: @sahhosseini',librarySource:'منبع',noResources:'هنوز منبع مستقلی برای نمایش ثبت نشده است.'},
 en:{gallery:'Gallery',galleryTitle:'Calligraphy Artworks',library:'Library',libraryTitle:'Sources & References',libraryIntro:'Poem sources, books, muraqqa and research references recorded in the archive.',events:'Events',eventSoon:'Coming soon',eventTitle:'Kelk Dabir Events',eventText:'Exhibitions, talks, workshops and events related to Persian calligraphy and archival research will be listed here.',about:'About',aboutTitle:'Kelk Dabir',aboutText:'Kelk Dabir is a searchable gateway for theoretical calligraphy practice, providing access to selected compositions by masters of Nastaliq and Shekasteh-Nastaliq.',search:'Search poems, calligraphers, poets, scripts, formats, techniques, periods, places and sources…',hint:'Multiple keywords can be searched together.',artists:'All calligraphers',poets:'All poets',scripts:'All scripts',formats:'All formats',techniques:'All techniques',periods:'All periods',count:'Artworks',poet:'Poet',artist:'Calligrapher',script:'Script',format:'Format',year:'Year',period:'Period',place:'Place',tech:'Technique / ornament',poemSource:'Poem source',imageSource:'Image source',additionalSource:'Additional source',description:'Description',date:'Archive date',view:'View artwork',none:'No artworks found.',noText:'No descriptive text',noData:'No data available.',close:'Close',open:'Open source',curator:'Curated by: @sahhosseini',librarySource:'Source',noResources:'No independent sources have been recorded yet.'}
};
const formatLabels={"Satr":'سطر',"سطر":'سطر',"Chalipa":'چلیپا',"چلیپا":'چلیپا',"Siyah Mashq":'سیاه‌مشق',"سیاه‌مشق":'سیاه‌مشق',"Daftari":'دفتری',"دفتری":'دفتری',"Qet'e":'قطعه',"قطعه":'قطعه',"Shekasteh":'شکسته',"Nasta'liq":'نستعلیق',"Nastaliq":'نستعلیق'};
function normalize(text){return String(text??'').toLowerCase().normalize('NFKC').replace(/ي/g,'ی').replace(/ى/g,'ی').replace(/ك/g,'ک').replace(/[‌‏]/g,' ').replace(/\s+/g,' ').trim();}
function archiveTimestamp(a){
  const raw=a.date||a.telegram_date||a.archive_date||a.post_date||a.created_at||'';
  const s=String(raw).trim();
  let m=s.match(/^(\d{1,2})[.\/-](\d{1,2})[.\/-](\d{4})(?:\s+(\d{1,2}):(\d{2})(?::(\d{2}))?)?/);
  if(m){
    const day=Number(m[1]), month=Number(m[2])-1, year=Number(m[3]);
    const hh=Number(m[4]||0), mm=Number(m[5]||0), ss=Number(m[6]||0);
    const t=Date.UTC(year,month,day,hh,mm,ss);
    if(!Number.isNaN(t)) return t;
  }
  const t=Date.parse(s);
  return Number.isNaN(t)?0:t;
}
function sortNewestFirst(list){return [...list].sort((a,b)=>archiveTimestamp(b)-archiveTimestamp(a));}

function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function langArr(item,field){const en=item[field+'_en']; const fa=item[field]; return currentLanguage==='en'?(Array.isArray(en)&&en.length?en:fa||[]):(fa||[]);}
function displayValue(item,field){return langArr(item,field).join(currentLanguage==='fa'?'، ':', ');}
async function loadData(){try{const r=await fetch('artworks_final.json?t='+Date.now());if(!r.ok)throw Error('artworks_final.json');artworks=await r.json();artworks=Array.isArray(artworks)?sortNewestFirst(artworks):[];filteredArtworks=[...artworks];populateFilters();renderGallery();renderLibrary();updateLanguageUI();}catch(e){console.error(e);gallery.innerHTML='<div class="load-error">'+labels[currentLanguage].noData+'</div>';}}
function counts(field){const m=new Map();artworks.forEach(a=>(a[field]||[]).forEach(v=>{if(v)m.set(v,(m.get(v)||0)+1);}));return m;}
function englishValue(field,v){for(const a of artworks){const i=(a[field]||[]).indexOf(v);if(i>=0&&a[field+'_en']?.[i])return a[field+'_en'][i];}return v;}
function fillSelect(select,field,defaultLabel){const prev=select.value;select.innerHTML='';const d=document.createElement('option');d.value='';d.textContent=defaultLabel;select.appendChild(d);[...counts(field).entries()].sort((a,b)=>b[1]-a[1]||String(a[0]).localeCompare(String(b[0]),'fa')).forEach(([v,n])=>{const o=document.createElement('option');o.value=v;let text=currentLanguage==='fa'?v:englishValue(field,v);if(field==='formats'&&currentLanguage==='fa')text=formatLabels[v]||v;o.textContent=text+' ('+n+')';select.appendChild(o);});if([...select.options].some(o=>o.value===prev))select.value=prev;}
function populateFilters(){fillSelect(artistFilter,'calligraphers',labels[currentLanguage].artists);fillSelect(poetFilter,'poets',labels[currentLanguage].poets);fillSelect(scriptFilter,'scripts',labels[currentLanguage].scripts);fillSelect(formatFilter,'formats',labels[currentLanguage].formats);fillSelect(techniqueFilter,'techniques',labels[currentLanguage].techniques);fillSelect(periodFilter,'periods',labels[currentLanguage].periods);}
function applyFilters(){const terms=normalize(searchInput.value).split(' ').filter(Boolean);const vals={artist:artistFilter.value,poet:poetFilter.value,script:scriptFilter.value,format:formatFilter.value,technique:techniqueFilter.value,period:periodFilter.value};filteredArtworks=sortNewestFirst(artworks.filter(a=>{const searchable=normalize([a.poem_text,a.text,a.description,a.year,a.date,a.poem_source,a.image_source,a.additional_source,a.source,...(a.poem_sources||[]).flatMap(x=>[x.label,x.url]),...(a.calligraphers||[]),...(a.calligraphers_en||[]),...(a.poets||[]),...(a.poets_en||[]),...(a.scripts||[]),...(a.scripts_en||[]),...(a.formats||[]),...(a.formats_en||[]),...(a.techniques||[]),...(a.techniques_en||[]),...(a.periods||[]),...(a.periods_en||[]),...(a.places||[]),...(a.places_en||[]),...(a.other_tags||[])].join(' '));return terms.every(t=>searchable.includes(t))&&(!vals.artist||(a.calligraphers||[]).includes(vals.artist))&&(!vals.poet||(a.poets||[]).includes(vals.poet))&&(!vals.script||(a.scripts||[]).includes(vals.script))&&(!vals.format||(a.formats||[]).includes(vals.format))&&(!vals.technique||(a.techniques||[]).includes(vals.technique))&&(!vals.period||(a.periods||[]).includes(vals.period))));renderGallery();}
function renderGallery(){gallery.innerHTML='';count.textContent=labels[currentLanguage].count+': '+filteredArtworks.length.toLocaleString(currentLanguage==='fa'?'fa-IR':'en-US');if(!filteredArtworks.length){gallery.innerHTML='<div class="no-results">'+labels[currentLanguage].none+'</div>';return;}filteredArtworks.forEach(a=>gallery.appendChild(card(a)));}
function card(a){const article=document.createElement('article');article.className='artwork-card';const img=document.createElement('img');img.loading='lazy';img.src=a.thumbnail||a.high_res||'';img.alt=displayValue(a,'calligraphers')||'Persian calligraphy';img.onerror=()=>{img.classList.add('image-missing');img.removeAttribute('src');};const info=document.createElement('div');info.className='artwork-info';const title=document.createElement('h3');title.textContent=preview(a.poem_text||a.text||labels[currentLanguage].noText);info.appendChild(title);addCard(info,labels[currentLanguage].artist,displayValue(a,'calligraphers'));addCard(info,labels[currentLanguage].poet,displayValue(a,'poets'));addCard(info,labels[currentLanguage].format,displayValue(a,'formats'));addCard(info,labels[currentLanguage].year,a.year);const b=document.createElement('button');b.className='view-button';b.textContent=labels[currentLanguage].view;b.onclick=()=>openArtwork(a);info.appendChild(b);article.append(img,info);return article;}
function addCard(c,label,value){if(!value)return;const p=document.createElement('p');p.innerHTML='<strong>'+esc(label)+':</strong> '+esc(value);c.appendChild(p);}
function preview(t){t=String(t||'').trim().replace(/\s+/g,' ');return t.length>105?t.slice(0,105)+'…':t;}
function addDetail(c,label,value){if(!value)return;const p=document.createElement('p');p.className='detail-row';p.innerHTML='<strong>'+esc(label)+':</strong> <span>'+esc(value).replace(/
/g,'<br>')+'</span>';c.appendChild(p);}
function addLinks(c,label,items,legacy){const arr=Array.isArray(items)?items.filter(x=>x&&x.url):[];if(!arr.length&&legacy){addDetail(c,label,legacy);return;}if(!arr.length)return;const p=document.createElement('p');p.className='detail-row';const s=document.createElement('strong');s.textContent=label+':';p.appendChild(s);const wrap=document.createElement('span');wrap.className='source-links';arr.forEach((x,i)=>{if(i)wrap.append(' · ');const a=document.createElement('a');a.href=x.url;a.target='_blank';a.rel='noopener noreferrer';a.textContent=x.label||labels[currentLanguage].open;wrap.appendChild(a);});p.appendChild(wrap);c.appendChild(p);}
function openArtwork(a){const modal=document.createElement('div');modal.className='artwork-modal';const inner=document.createElement('div');inner.className='modal-inner';const close=document.createElement('button');close.className='modal-close';close.textContent='×';close.onclick=()=>modal.remove();const img=document.createElement('img');img.className='high-res-image';img.src=a.high_res||a.thumbnail||'';img.alt=displayValue(a,'calligraphers')||'Persian calligraphy';img.onerror=()=>{img.classList.add('image-missing');img.removeAttribute('src');};const details=document.createElement('div');details.className='modal-details';addDetail(details,currentLanguage==='fa'?'متن':'Text',a.poem_text||a.text);addDetail(details,labels[currentLanguage].artist,displayValue(a,'calligraphers'));addDetail(details,labels[currentLanguage].poet,displayValue(a,'poets'));addDetail(details,labels[currentLanguage].script,displayValue(a,'scripts'));addDetail(details,labels[currentLanguage].format,displayValue(a,'formats'));addDetail(details,labels[currentLanguage].tech,displayValue(a,'techniques'));addDetail(details,labels[currentLanguage].year,a.year);addDetail(details,labels[currentLanguage].period,displayValue(a,'periods'));addDetail(details,labels[currentLanguage].place,displayValue(a,'places'));addDetail(details,labels[currentLanguage].description,a.description);addLinks(details,labels[currentLanguage].poemSource,a.poem_sources,a.poem_source);addLinks(details,labels[currentLanguage].imageSource,a.image_sources,a.image_source);addLinks(details,labels[currentLanguage].additionalSource,a.additional_sources,a.additional_source);addDetail(details,labels[currentLanguage].date,a.date);inner.append(close,img,details);modal.appendChild(inner);document.body.appendChild(modal);modal.addEventListener('click',e=>{if(e.target===modal)modal.remove();});}
function sourceMap(){const m=new Map();artworks.forEach(a=>{(a.poem_sources||[]).forEach(s=>{if(s?.url)m.set(s.url,s.label||s.url);});[a.image_source,a.additional_source].forEach(u=>{if(/^https?:\/\//i.test(String(u||'')))m.set(u,String(u));});});return [...m.entries()].sort((a,b)=>a[1].localeCompare(b[1],'fa'));}
function renderLibrary(){const box=$('libraryGrid');box.innerHTML='';const sources=sourceMap();if(!sources.length){box.innerHTML='<div class="no-results">'+labels[currentLanguage].noResources+'</div>';return;}sources.forEach(([url,label])=>{const c=document.createElement('article');c.className='resource-card';const h=document.createElement('h3');h.textContent=label;const p=document.createElement('p');p.textContent=url;const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.textContent=labels[currentLanguage].open;c.append(h,p,a);box.appendChild(c);});}
function showSection(id){document.querySelectorAll('.page-section').forEach(s=>s.classList.toggle('active-section',s.id===id));document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===id));if(id==='gallery')renderGallery();if(id==='library')renderLibrary();}
document.querySelectorAll('[data-nav]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();const id=a.dataset.nav;history.replaceState(null,'','#'+id);showSection(id);}));
function updateLanguageUI(){const l=labels[currentLanguage];document.documentElement.lang=currentLanguage;document.documentElement.dir=currentLanguage==='fa'?'rtl':'ltr';$('galleryEyebrow').textContent=l.gallery;$('galleryTitle').textContent=l.galleryTitle;$('libraryEyebrow').textContent=l.library;$('libraryTitle').textContent=l.libraryTitle;$('libraryIntro').textContent=l.libraryIntro;$('eventsEyebrow').textContent=l.events;$('eventsTitle').textContent=l.events;$('eventDate').textContent=l.eventSoon;$('eventCardTitle').textContent=l.eventTitle;$('eventCardText').textContent=l.eventText;$('aboutEyebrow').textContent=l.about;$('aboutTitle').textContent=l.aboutTitle;$('aboutText').textContent=l.aboutText;$('aboutCurator').textContent=l.curator;$('footerText').textContent=l.curator;searchInput.placeholder=l.search;$('searchHint').textContent=l.hint;languageToggle.textContent=currentLanguage==='fa'?'English':'فارسی';document.querySelector('[data-nav="gallery"]').textContent=l.gallery;document.querySelector('[data-nav="library"]').textContent=l.library;document.querySelector('[data-nav="events"]').textContent=l.events;document.querySelector('[data-nav="about"]').textContent=l.about;populateFilters();renderGallery();renderLibrary();}
[searchInput,artistFilter,poetFilter,scriptFilter,formatFilter,techniqueFilter,periodFilter].forEach(el=>el.addEventListener(el.tagName==='INPUT'?'input':'change',applyFilters));
languageToggle.addEventListener('click',()=>{currentLanguage=currentLanguage==='fa'?'en':'fa';localStorage.setItem('kelk_language',currentLanguage);updateLanguageUI();});
const initial=location.hash.replace('#','');showSection(['gallery','library','events','about'].includes(initial)?initial:'gallery');
loadData();
