let artworks=[], lang='fa';
const $=id=>document.getElementById(id);
const faLabels={artistFilter:'همه خوشنویسان',poetFilter:'همه شاعران',scriptFilter:'همه خطوط',formatFilter:'همه قالب‌ها',ornamentFilter:'آرایه‌ها',periodFilter:'همه دوره‌ها'};
const enLabels={artistFilter:'All calligraphers',poetFilter:'All poets',scriptFilter:'All scripts',formatFilter:'All formats',ornamentFilter:'Ornaments',periodFilter:'All periods'};
const en=v=>Array.isArray(v)?v.map(x=>x):[];
function values(field){const c=new Map();for(const a of artworks){for(const v of (a[field]||[])){c.set(v,(c.get(v)||0)+1)}}return [...c.entries()].sort((a,b)=>b[1]-a[1]||String(a[0]).localeCompare(String(b[0])))}
function fill(id,field,multi=false){const s=$(id);s.innerHTML='';if(!multi){let o=document.createElement('option');o.value='';o.textContent=(lang==='fa'?faLabels[id]:enLabels[id]);s.append(o)}else{let o=document.createElement('option');o.value='';o.textContent=(lang==='fa'?'آرایه‌ها — Ctrl را برای چندانتخاب نگه دارید':'Ornaments — Ctrl/Cmd for multiple');s.append(o)}for(const [v,n] of values(field)){let o=document.createElement('option');o.value=v;o.textContent=`${lang==='fa'?v:(artworks.find(a=>(a[field]||[]).includes(v))?.[field+'_en']?.[(artworks.find(a=>(a[field]||[]).includes(v))?.[field]||[]).indexOf(v)]||v)} (${n})`;s.append(o)}}
function populate(){fill('artistFilter','calligraphers');fill('poetFilter','poets');fill('scriptFilter','scripts');fill('formatFilter','formats');fill('ornamentFilter','ornaments',true);fill('periodFilter','periods')}
function searchable(a){return [a.poem_text,a.description,...a.poets,...a.calligraphers,...a.scripts,...a.formats,...a.ornaments,...a.periods,...a.places,...a.other_tags,...a.poem_source,...a.image_source,...a.additional_source].filter(Boolean).join(' ').toLowerCase()}
function selected(id){return [...$(id).selectedOptions].map(o=>o.value).filter(Boolean)}
function apply(){const q=$('search').value.trim().toLowerCase(), artist=$('artistFilter').value, poet=$('poetFilter').value, script=$('scriptFilter').value, format=$('formatFilter').value, periods=$('periodFilter').value, orn=selected('ornamentFilter');let r=artworks.filter(a=>(!q||searchable(a).includes(q))&&(!artist||(a.calligraphers||[]).includes(artist))&&(!poet||(a.poets||[]).includes(poet))&&(!script||(a.scripts||[]).includes(script))&&(!format||(a.formats||[]).includes(format))&&(!periods||(a.periods||[]).includes(periods))&&(!orn.length||orn.every(x=>(a.ornaments||[]).includes(x))));render(r)}
function render(list){$('count').textContent=(lang==='fa'?`تعداد آثار: ${list.length}`:`Works: ${list.length}`);$('galleryGrid').innerHTML=list.map(a=>{const title=(a.poets||[]).join('، ')||'شاعر نامعلوم';const img=a.thumbnail||a.high_res;return `<article class="card"><img src="${img}" loading="lazy" alt="${(a.poets||[]).join('، ')}"><div class="card-body"><div>${title}</div><div class="meta">خوشنویس: ${(a.calligraphers||[]).join('، ')||'—'}</div><div class="meta">${(a.formats||[]).join('، ')} ${a.year?' | سال '+a.year:''}</div><div class="chips">${(a.ornaments||[]).map(x=>`<span class="chip">${x}</span>`).join('')}</div><button onclick='openArt(${JSON.stringify(a).replace(/'/g,"&#39;")})'>${lang==='fa'?'مشاهده اثر':'View work'}</button></div></article>`}).join('')}
function openArt(a){$('modalImg').src=a.high_res||a.thumbnail;$('modalText').innerHTML=`<div>${a.poem_text||''}</div><p>خوشنویس: ${(a.calligraphers||[]).join('، ')||'—'}<br>شاعر: ${(a.poets||[]).join('، ')||'—'}<br>خط: ${(a.scripts||[]).join('، ')||'—'}<br>قالب: ${(a.formats||[]).join('، ')||'—'}<br>آرایه: ${(a.ornaments||[]).join('، ')||'—'}<br>دوره: ${(a.periods||[]).join('، ')||'—'}<br>سال: ${a.year||'—'}</p><div class="source">منبع شعر: ${(a.poem_source||[]).map(x=>x.startsWith('http')?`<a href="${x}" target="_blank">${x}</a>`:x).join('، ')||'—'}<br>منبع عکس/فایل: ${(a.image_source||[]).map(x=>x.startsWith('http')?`<a href="${x}" target="_blank">${x}</a>`:x).join('، ')||'—'}<br>منبع اضافه: ${(a.additional_source||[]).join('، ')||'—'}</div>`;$('modal').classList.add('open')}
$('close').onclick=()=>$('modal').classList.remove('open');$('modal').onclick=e=>{if(e.target===$('modal'))$('modal').classList.remove('open')};
$('search').oninput=apply;for(const id of ['artistFilter','poetFilter','scriptFilter','formatFilter','ornamentFilter','periodFilter'])$(id).onchange=apply;
$('languageToggle').onclick=()=>{lang=lang==='fa'?'en':'fa';document.documentElement.lang=lang;document.documentElement.dir=lang==='fa'?'rtl':'ltr';document.querySelectorAll('[data-fa]').forEach(e=>e.textContent=e.dataset[lang]);$('languageToggle').textContent=lang==='fa'?'English':'فارسی';populate();apply()};
async function init(){try{const r=await fetch('artworks_final.json?t='+Date.now());artworks=await r.json();artworks.sort((a,b)=>String(b.date).localeCompare(String(a.date)));populate();render(artworks);const l=await fetch('library.json');const lib=await l.json();$('libraryGrid').innerHTML=lib.map(x=>`<div class="library-item"><b>${x.name}</b><div>${x.count} اثر</div>${x.url?`<a href="${x.url}" target="_blank">منبع</a>`:''}</div>`).join('')}catch(e){console.error(e);$('galleryGrid').innerHTML='<div class="empty">خطا در بارگذاری داده‌های نگارخانه.</div>'}}init();